import json, re, os
from pathlib import Path
from PyPDF2 import PdfReader

# Build the extracted_text.txt from the PDFs first
pdf_dir = Path("Test")
out_file = Path("extracted_text.txt")
with out_file.open("w", encoding="utf-8") as out:
    for pdf_path in sorted(pdf_dir.glob("*.pdf")):
        out.write("="*60 + "\n")
        out.write(f"=== {pdf_path.name} ===\n")
        out.write("="*60 + "\n")
        try:
            reader = PdfReader(str(pdf_path))
            for i, page in enumerate(reader.pages):
                txt = page.extract_text()
                if txt:
                    out.write(f"--- Page {i+1} ---\n")
                    out.write(txt + "\n")
        except Exception as e:
            out.write(f"Error leyendo {pdf_path.name}: {e}\n")

# Load the existing questions JSON
with open('questions.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Load the extracted text from PDFs (generated by extract_pdfs.py)
with open('extracted_text.txt', 'r', encoding='utf-8') as f:
    txt = f.read()

# Mapping of PDF file name to subject name in JSON
pdf_to_subject = {
    'Test Final.pdf': 'Test Final',
    'Test Modulo 1.pdf': 'Test Modulo 1',
    'Test Modulo 2.pdf': 'Test Modulo 2',
    'Test Modulo 3.pdf': 'Test Modulo 3',
    'Test Modulo 4.pdf': 'Test Modulo 4',
}

# Helper to find the answer option that follows a "Puedes encontrar la solución..." line
def extract_answer(block):
    # Look for the line that contains "solución" and then the next line starting with A./B./C./D.
    lines = block.splitlines()
    for i, line in enumerate(lines):
        if 'solución' in line.lower():
            # Search forward for the next option line
            for j in range(i+1, len(lines)):
                opt = lines[j].strip()
                m = re.match(r'([ABCD])\.\s*(.+)', opt)
                if m:
                    return f"{m.group(1)}. {m.group(2).strip()}"
    return None

# Split the extracted text by PDF sections
sections = txt.split('============================================================')

for sec in sections:
    # Identify which PDF this section belongs to
    match = re.search(r'===\s+([^=]+)\.pdf\s+===', sec)
    if not match:
        continue
    pdf_name = match.group(1).strip() + '.pdf'
    subject = pdf_to_subject.get(pdf_name)
    if not subject:
        continue
    # Find the JSON entry for this subject
    subj_entry = next((s for s in data if s['subject'] == subject), None)
    if not subj_entry:
        continue
    # Split into individual question blocks – each starts with a line that begins with a number and a dot
    question_blocks = re.split(r'\n\s*\d+\.', sec)[1:]  # first split part is header
    for idx, qblock in enumerate(question_blocks):
        answer = extract_answer(qblock)
        if answer:
            try:
                subj_entry['questions'][idx]['correctAnswer'] = answer
            except IndexError:
                # If the counts differ, ignore silently – we prefer not to crash
                pass

# Write back the updated JSON with proper formatting
with open('questions.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print('questions.json actualizado con respuestas encontradas.')